import './style.css';
import './broadcast-fit.css';
import './interaction.css';
import './rooms.css';
import {createRenderer,type Renderer} from './renderers.ts';
import type {RoomView,HostAction} from '../src/room-types.ts';
import type {Team} from '../src/types.ts';
const $=(id:string)=>document.getElementById(id)!;
const teamName=(team:Team|null)=>team==='red'?'Đỏ':team==='black'?'Đen':'Chưa chọn đội';
const brand=`<div class="wordmark"><span class="seal">棋</span><div>KỲ HỘI<small>CỜ TƯỚNG CỘNG ĐỒNG</small></div></div>`;
let room:RoomView|null=null,renderer:Renderer|undefined,socket:WebSocket|undefined,reconnect:ReturnType<typeof setTimeout>|undefined;
let generation=0,offset=0,rosterKey='',connected=false;
const showingLive=new URLSearchParams(location.search).get('view')==='live';
const value=(id:string)=>(document.getElementById(id) as HTMLInputElement).value;
const number=(id:string)=>Number(value(id));
function hint(message:string){const output=document.getElementById(room?'result':'lobby-message');if(output)output.textContent=message;}
async function api(path:string,data?:unknown){const response=await fetch(path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error??'Không thực hiện được');return result;}
function remember(name:string){localStorage.setItem('kyhoi-name',name);}
function lobby(message=''){
  generation++;clearTimeout(reconnect);socket?.close();socket=undefined;renderer?.destroy();renderer=undefined;room=null;connected=false;document.body.className='lobby-body';
  $('app').innerHTML=`<main class="lobby"><header>${brand}<span class="lobby-badge">MỘT IP · MỘT NGƯỜI</span></header><section class="lobby-intro"><p class="eyebrow">RỦ BẠN VÀO PHÒNG. CÙNG NHAU ĐI MỘT NƯỚC HAY.</p><h1>Bàn cờ của <em>mọi người.</em></h1><p>Không tài khoản, không mật khẩu. Đặt tên và chọn cách vào chơi.</p></section><div class="entry-grid"><form id="create-form" class="entry-card"><span class="card-number">01 / LÀM CHỦ BÀN CỜ</span><h2>Tạo mã phòng</h2><p>Tạo trận mới, gửi mã cho bạn bè. Bạn là host.</p><label>Tên của bạn<input id="create-name" required maxlength="40" placeholder="Bạn tên gì?"></label><label>Tên phòng<input id="room-title" maxlength="60" placeholder="Cờ chiều cùng bạn bè"></label><div class="form-row"><label>Game<select id="game"><option value="xiangqi">Cờ tướng</option><option value="tictactoe">Caro 3 × 3</option></select></label><label>Tổng số người<input id="max-people" type="number" min="1" max="200" value="20" required></label></div><div class="form-row"><label>Chỗ đội Đỏ<input id="red-limit" type="number" min="1" max="100" value="10" required></label><label>Chỗ đội Đen<input id="black-limit" type="number" min="1" max="100" value="10" required></label></div><div class="form-row"><label>Mỗi lượt (giây)<input id="turn-seconds" type="number" min="5" max="300" value="30" required></label><label>Cả trận (phút)<input id="match-minutes" type="number" min="1" max="240" value="30" required></label></div><label class="check"><input id="allow-guests" type="checkbox" checked> Cho phép guest xem bàn cờ</label><button id="create-room" class="primary">Tạo mã & bắt đầu trận ↗</button></form><form id="join-form" class="entry-card join-card"><span class="card-number">02 / ĐÃ CÓ LỜI MỜI?</span><h2>Nhập mã phòng</h2><p>Vào cùng một bàn cờ, chọn đội và góp một phiếu.</p><label>Tên của bạn<input id="join-name" required maxlength="40" placeholder="Tên hiển thị trong phòng"></label><label>Mã phòng<input id="join-code" required minlength="6" maxlength="6" placeholder="VD: K7MX2P" autocomplete="off" spellcheck="false"></label><label class="check"><input id="as-guest" type="checkbox"> Vào làm guest · chỉ xem, không vote</label><button id="join-room" class="primary">Vào phòng →</button><div class="room-rules"><p><b>Đội đã chọn sẽ khóa.</b><br>Muốn đổi đội? Gửi yêu cầu cho host.</p><p><b>Phiếu thuộc về đội mình.</b><br>Đội đối phương và guest không xem được.</p><p><b>Hết giờ là đi.</b><br>Không có phiếu? Chọn ngẫu nhiên một nước hợp lệ.</p></div></form></div><output id="lobby-message" role="status" aria-live="polite"></output><footer>Cùng IP sẽ là cùng một người, kể cả khi mở nhiều tab hoặc đổi tên.</footer></main>`;
  const saved=localStorage.getItem('kyhoi-name')??'';(document.getElementById('create-name') as HTMLInputElement).value=saved;(document.getElementById('join-name') as HTMLInputElement).value=saved;hint(message);
  $('create-form').onsubmit=async(event)=>{event.preventDefault();const button=$('create-room') as HTMLButtonElement;button.disabled=true;try{const name=value('create-name');const created=await api('/api/rooms',{name,title:value('room-title'),settings:{game:value('game'),maxPeople:number('max-people'),redLimit:number('red-limit'),blackLimit:number('black-limit'),allowGuests:(document.getElementById('allow-guests') as HTMLInputElement).checked,turnSeconds:number('turn-seconds'),matchMinutes:number('match-minutes')}});remember(name);await enter(created);}catch(error){hint((error as Error).message);button.disabled=false;}};
  $('join-form').onsubmit=async(event)=>{event.preventDefault();const button=$('join-room') as HTMLButtonElement;button.disabled=true;try{const name=value('join-name');const joined=await api(`/api/rooms/${value('join-code').trim().toUpperCase()}/join`,{name,kind:(document.getElementById('as-guest') as HTMLInputElement).checked?'guest':'player'});remember(name);await enter(joined);}catch(error){hint((error as Error).message);button.disabled=false;}};
}
async function command(action:string,data:unknown){if(!room)return;const code=room.code;try{const response=await api(`/api/rooms/${code}/${action}`,data);if(!room||room.code!==code)return;
  if(response.left||response.closed){history.replaceState(null,'','/');lobby(response.closed?'Phòng đã đóng.':'Bạn đã rời phòng. Có thể nhập mã để quay lại.');return;}
  update(response.room??response);if(action==='vote')hint(response.accepted?'Đã ghi nhận phiếu. Kéo nước khác để đổi phiếu.':({ 'wrong-team':'Chưa đến lượt đội của bạn.','stale-window':'Cửa sổ đã hết hạn.','window-closed':'Đã đóng bình chọn.','illegal-move':'Nước đi không hợp lệ.'} as Record<string,string>)[response.reason]??'Phiếu chưa được ghi nhận.');else hint(action==='request'?'Đã gửi yêu cầu. Chờ host duyệt.':'Đã cập nhật.');
 }catch(error){hint((error as Error).message);}}
function canVote(){if(!room||!connected||room.game.phase!=='voting'||Date.now()+offset>=room.game.deadline){hint('Lượt đang đóng hoặc kết nối bị gián đoạn.');return false;}if(room.me.kind==='guest'||!room.me.team){hint('Bạn cần được vào đội để bình chọn.');return false;}if(room.me.team!==room.game.activeTeam){hint('Chưa đến lượt đội của bạn.');return false;}return true;}
async function enter(initial:RoomView){
  const gen=++generation;clearTimeout(reconnect);socket?.close();renderer?.destroy();renderer=undefined;room=initial;connected=true;rosterKey='';history.replaceState(null,'',`/room/${initial.code}${showingLive?'?view=live':''}`);document.body.className=showingLive?'':'with-operator room-body';
  $('app').innerHTML=`<main class="broadcast"><header class="masthead">${brand}<button id="copy-code" class="room-code" title="Sao chép mã phòng"></button></header><section class="intro"><p class="eyebrow" id="room-title-display"></p><h1>Hai đội. <em>Một bàn cờ.</em></h1><p id="identity-line"></p></section><section class="teams"><div class="team red"><div>ĐỘI ĐỎ<small id="red-count"></small></div><strong>帥</strong></div><span class="versus">VS</span><div class="team black"><div>ĐỘI ĐEN<small id="black-count"></small></div><strong>將</strong></div></section><section class="turn"><div><span id="phase-label"></span><small id="round"></small></div><div class="clock"><span id="window"></span><strong id="timer">--:--</strong></div></section><div class="time-track"><div id="time-fill"></div></div><section class="board-wrap"><div class="board-label"><span id="board-title"></span><span>ĐEN ↑ &nbsp; ĐỎ ↓</span></div><div id="board"></div><div class="board-foot"><span id="last-move"></span><span id="connection"></span></div></section><section class="votes"><div class="section-heading"><h2 id="votes-title">Bình chọn của đội</h2><span id="vote-count"></span></div><div id="vote-list"></div><p id="notice" class="notice"></p></section><section class="how-to"><span class="eyebrow">BÌNH CHỌN TRỰC TIẾP TRÊN BÀN</span><div><span class="step">↗</span><p>Kéo thả quân<code>Hoặc bấm ô đi → ô đến</code></p></div><div><span class="step">◷</span><p>Thời gian trận còn lại<code id="match-timer">--:--</code></p></div><small>1 IP = 1 phiếu · Không có phiếu thì tự đi ngẫu nhiên</small></section><footer><span>KỲ HỘI / PHÒNG RIÊNG</span><span id="room-count"></span></footer></main>${showingLive?'':`<aside class="operator room-panel"><p class="eyebrow" id="role-label"></p><h2 id="my-name"></h2><p id="my-team"></p><div id="team-actions" class="actions"></div><output id="result" role="status" aria-live="polite">Kéo quân hoặc bấm hai ô để bình chọn.</output><details><summary>Đổi tên hiển thị</summary><form id="rename-form"><input id="rename" required maxlength="40" aria-label="Tên hiển thị"><button>Đổi tên</button></form></details><section id="host-panel" hidden><h3>Điều khiển phòng</h3><p class="admin-tip">Kéo thẻ thành viên vào đội bên dưới, hoặc dùng nút Chuyển.</p><div class="team-dropzones"><div class="team-drop" data-team="red">Đỏ</div><div class="team-drop" data-team="black">Đen</div><div class="team-drop" data-team="guest">Guest</div></div><div class="actions"><button id="restart-room">Ván mới</button><button id="close-room" class="danger">Đóng phòng</button></div><h3>Yêu cầu đổi đội</h3><div id="requests"></div></section><h3>Thành viên <span id="members-count"></span></h3><div id="members"></div><section id="bans-section" hidden><h3>IP đã bị ban</h3><div id="bans"></div></section><details><summary>Cấu hình trận</summary><p id="room-config"></p></details><button id="leave-room" class="leave-button">Rời phòng</button></aside>`}`;
  $('copy-code').onclick=()=>{if(room)void navigator.clipboard.writeText(room.code).then(()=>hint('Đã sao chép mã phòng.')).catch(()=>hint(`Mã phòng: ${room?.code}`));};
  if(!showingLive){$('leave-room').onclick=()=>void command('leave',{});$('rename-form').onsubmit=event=>{event.preventDefault();remember(value('rename'));void command('name',{name:value('rename')});};$('restart-room').onclick=()=>{if(confirm('Bắt đầu ván mới trong phòng này?'))void host('restart');};$('close-room').onclick=()=>{if(confirm('Đóng phòng cho tất cả mọi người?'))void host('close');};
    document.querySelectorAll<HTMLElement>('.team-drop').forEach(zone=>{zone.ondragover=event=>{if(room?.isHost){event.preventDefault();zone.classList.add('drag-over');}};zone.ondragleave=()=>zone.classList.remove('drag-over');zone.ondrop=event=>{event.preventDefault();zone.classList.remove('drag-over');const id=event.dataTransfer?.getData('text/plain');if(id&&room?.isHost)void host('move',id,zone.dataset.team as Team|'guest');};});}
  update(initial);
  const newRenderer=await createRenderer(initial.game.gameKind,$('board'),showingLive?undefined:{canVote,onVote:(move,windowId)=>void command('vote',{move,windowId}),onHint:hint});
  if(gen!==generation){newRenderer.destroy();return;}renderer=newRenderer;if(room)renderer.update(room.game,room.myVote);
  connect(initial.code,gen);
}
async function host(action:HostAction,targetId?:string,team?:Team|'guest'){await command('host',{action,targetId,team});}
function button(label:string,fn:()=>void,className=''){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=className;b.onclick=fn;return b;}
function roster(view:RoomView){
  if(showingLive)return;const key=JSON.stringify([view.me,view.members,view.requests,view.bans,view.isHost]);if(key===rosterKey)return;rosterKey=key;
  $('role-label').textContent=view.isHost?'HOST · QUẢN LÝ PHÒNG':view.me.kind==='guest'?'GUEST · CHỈ XEM':'NGƯỜI CHƠI';$('my-name').textContent=view.me.name;($('rename') as HTMLInputElement).value=view.me.name;
  $('my-team').textContent=`${view.me.kind==='guest'?'Guest':teamName(view.me.team)}${view.me.request?` · Đang xin sang ${teamName(view.me.request)}`:''}`;
  const actions=$('team-actions');actions.replaceChildren();
  if(!view.me.team&&view.me.kind==='player')for(const team of ['red','black']as const)actions.append(button(`Vào ${teamName(team)}`,()=>void command('team',{team})));
  else if(view.me.team){const team=view.me.team==='red'?'black':'red';actions.append(button(`Xin sang ${teamName(team)}`,()=>void command('request',{team})));}
  else for(const team of ['red','black']as const)actions.append(button(`Xin vào ${teamName(team)}`,()=>void command('request',{team})));
  $('host-panel').hidden=!view.isHost;$('bans-section').hidden=!view.isHost||!view.bans.length;
  $('members-count').textContent=`${view.members.length}/${view.settings.maxPeople}`;
  $('members').replaceChildren(...view.members.map(member=>{const card=document.createElement('div');card.className=`member-card ${member.team??'guest'}`;card.dataset.member=member.id;card.draggable=view.isHost;
    card.ondragstart=event=>event.dataTransfer?.setData('text/plain',member.id);
    const name=document.createElement('strong');name.textContent=member.name+(member.id===view.me.id?' · bạn':'')+(member.id===view.hostId?' ♛':'');const desc=document.createElement('small');desc.textContent=member.kind==='guest'?'Guest':teamName(member.team);card.append(name,desc);
    if(view.isHost){const controls=document.createElement('div');controls.className='member-controls';const select=document.createElement('select');select.setAttribute('aria-label',`Chuyển đội ${member.name}`);for(const [v,label]of [['red','Đỏ'],['black','Đen'],['guest','Guest']])select.add(new Option(label,v));select.value=member.team??'guest';controls.append(select,button('Chuyển',()=>void host('move',member.id,select.value as Team|'guest')));if(member.id!==view.hostId)controls.append(button('Kick',()=>void host('kick',member.id)),button('Ban',()=>void host('ban',member.id),'danger'));card.append(controls);}return card;}));
  $('requests').replaceChildren();if(!view.requests.length)$('requests').textContent='Chưa có yêu cầu.';for(const member of view.requests){const row=document.createElement('div');row.className='request-row';const text=document.createElement('span');text.textContent=`${member.name} → ${teamName(member.request)}`;row.append(text,button('Duyệt',()=>void host('approve',member.id)),button('Từ chối',()=>void host('reject',member.id)));$('requests').append(row);}
  $('bans').replaceChildren(...view.bans.map(member=>{const row=document.createElement('div');row.className='request-row';const text=document.createElement('span');text.textContent=member.name;row.append(text,button('Gỡ ban',()=>void host('unban',member.id)));return row;}));
}
function update(view:RoomView){
  if(room&&room.code!==view.code)return;const previous=room;room=view;offset=view.game.serverNow-Date.now();
  if(previous?.me.team!==view.me.team)renderer?.clearSelection();renderer?.update(view.game,view.myVote);
  const s=view.game;$('copy-code').textContent=`${view.code} ⧉`;$('room-title-display').textContent=view.title;$('identity-line').textContent=`${view.me.name} · ${view.isHost?'Host':view.me.kind==='guest'?'Guest':teamName(view.me.team)} · 1 IP = 1 người`;
  $('red-count').textContent=`${view.members.filter(m=>m.team==='red').length}/${view.settings.redLimit} thành viên`;$('black-count').textContent=`${view.members.filter(m=>m.team==='black').length}/${view.settings.blackLimit} thành viên`;
  $('phase-label').textContent=s.phase==='finished'?(s.outcome?.winner?`ĐỘI ${teamName(s.outcome.winner).toUpperCase()} THẮNG`:'TRẬN ĐẤU KẾT THÚC · HÒA'):s.phase==='revealing'?'NƯỚC ĐI ĐÃ ĐƯỢC CHỌN':`ĐẾN LƯỢT ĐỘI ${teamName(s.activeTeam).toUpperCase()}`;
  $('round').textContent=s.phase==='finished'?s.outcome?.reason??'Kết thúc':`Ván ${s.gameId} · Vòng ${s.roundId} · Lượt ${s.turnId}`;$('window').textContent=`W${s.windowId}`;
  $('board-title').textContent=s.gameKind==='xiangqi'?'BÀN CỜ TƯỚNG':'CARO 3 × 3';$('last-move').textContent=s.lastMove?`Vừa đi: ${s.lastMove}`:'Bình chọn nước đầu tiên';$('connection').textContent=connected?'● Đã kết nối':'○ Đang kết nối lại';
  $('votes-title').textContent=view.canSeeVotes?`Bình chọn đội ${teamName(s.activeTeam)}`:'Phiếu đội đối phương được ẩn';$('vote-count').textContent=view.canSeeVotes?`${s.voterCount} PHIẾU`:'RIÊNG TƯ';
  const list=$('vote-list');list.replaceChildren();const rows=Object.entries(s.tally).sort((a,b)=>b[1]-a[1]).slice(0,3);
  if(!rows.length){const p=document.createElement('p');p.className='empty';p.textContent=s.phase==='finished'?'Host có thể bắt đầu ván mới.':!view.canSeeVotes?(view.me.kind==='guest'?'Guest chỉ xem bàn cờ, không xem phiếu.':'Bạn chỉ xem được bình chọn của đội mình.'):'Chưa có phiếu. Hết giờ sẽ đi một nước ngẫu nhiên hợp lệ.';list.append(p);}
  for(const [move,count]of rows){const row=document.createElement('div');row.className='vote-row';const code=document.createElement('code');code.textContent=move;const bar=document.createElement('div');bar.className='vote-bar';const fill=document.createElement('i');fill.style.width=`${100*count/Math.max(1,s.voterCount)}%`;bar.append(fill);const label=document.createElement('b');label.textContent=String(count);row.append(code,bar,label);list.append(row);}
  $('notice').textContent=view.myVote?`Phiếu của bạn: ${view.myVote}`:view.me.request?`Yêu cầu sang ${teamName(view.me.request)} đang chờ host duyệt.`:'Đội đã chọn sẽ khóa; chỉ host được duyệt hoặc điều chuyển.';$('room-count').textContent=`${view.members.length}/${view.settings.maxPeople} NGƯỜI`;
  if(!showingLive)$('room-config').textContent=`${view.settings.turnSeconds}s/lượt · ${view.settings.matchMinutes} phút/trận · ${view.settings.allowGuests?'Cho phép':'Không cho'} guest. Host rời phòng vẫn giữ quyền và một chỗ để quay lại.`;
  roster(view);
}
function connect(code:string,gen:number){if(gen!==generation)return;socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/${code}`);socket.onopen=()=>{connected=true;};socket.onmessage=event=>{if(gen!==generation)return;const data=JSON.parse(event.data);if(data.type==='removed'){history.replaceState(null,'','/');lobby(data.message);}else if(data.room)update(data.room);};socket.onclose=()=>{if(gen!==generation)return;connected=false;renderer?.clearSelection();$('connection').textContent='○ Đang kết nối lại';reconnect=setTimeout(()=>connect(code,gen),2000);};socket.onerror=()=>socket?.close();}
const time=(ms:number)=>{const seconds=Math.max(0,Math.ceil(ms/1000));return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;};
setInterval(()=>{if(!room)return;const now=Date.now()+offset,finished=room.game.phase==='finished';$('timer').textContent=!connected?'--:--':finished?'00:00':time(room.game.deadline-now);$('match-timer').textContent=finished?'00:00':time(room.matchDeadline-now);$('time-fill').style.width=`${finished?0:Math.min(100,Math.max(0,100*(room.game.deadline-now)/(room.settings.turnSeconds*1000)))}%`;},100);
const code=/^\/room\/([A-Za-z2-9]{6})$/.exec(location.pathname)?.[1];
if(code){try{await enter(await api(`/api/rooms/${code}`));}catch(error){lobby((error as Error).message);($('join-code') as HTMLInputElement).value=code.toUpperCase();}}else lobby();
