import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {RoomManager,canonicalIp,validateSettings} from '../src/rooms.ts';
import {createRoomServer} from '../src/room-server.ts';
function setup(){let now=100000;const dir=mkdtempSync(join(tmpdir(),'kyhoi-rooms-'));let manager=new RoomManager(dir,()=>now);const host=manager.identity('10.0.0.1'),red=manager.identity('10.0.0.2'),black=manager.identity('10.0.0.3'),guest=manager.identity('10.0.0.4');const room=manager.create(host,'Host','Test',{game:'tictactoe',turnSeconds:5,matchMinutes:1});return {dir,host,red,black,guest,room,get manager(){return manager;},advance(ms:number){now+=ms;manager.tick();},restart(){manager.close();manager=new RoomManager(dir,()=>now);return manager.get(room.meta.code);}};}
test('IP identity normalizes mapped and loopback addresses and survives restart',()=>{const h=setup();assert.equal(canonicalIp('::ffff:10.0.0.1'),'10.0.0.1');assert.equal(h.manager.identity('::ffff:10.0.0.1'),h.host);assert.equal(h.manager.identity('::ffff:a00:1'),h.host);assert.equal(h.manager.identity('::1'),h.manager.identity('127.0.0.1'));const id=h.manager.identity('2001:db8::1');assert.equal(h.manager.identity('2001:0db8:0000:0000:0000:0000:0000:0001'),id);h.restart();assert.equal(h.manager.identity('2001:db8::1'),id);h.manager.close();});
test('same IP rejoining changes name but not identity, team, seat, or vote count',()=>{const h=setup();const r=h.room;r.join(h.red,'First','player');r.chooseTeam(h.red,'red');r.vote(h.red,r.view(h.red).game.windowId,'1');r.join(h.red,'Second','guest');assert.equal(r.view(h.host).members.length,2);assert.equal(r.view(h.red).me.name,'Second');assert.equal(r.view(h.red).me.kind,'player');assert.equal(r.view(h.red).myVote,'1');r.vote(h.red,r.view(h.red).game.windowId,'2');assert.deepEqual(r.view(h.host).game.tally,{'2':1});h.manager.close();});
test('team lock survives leave/rejoin; host approval clears old vote and changes side',()=>{const h=setup(),r=h.room;r.join(h.red,'Red','player');r.chooseTeam(h.red,'red');r.vote(h.red,r.view(h.red).game.windowId,'1');assert.throws(()=>r.chooseTeam(h.red,'black'),/khóa/);r.requestTeam(h.red,'black');assert.equal(r.view(h.host).requests.length,1);assert.equal(r.view(h.red).me.team,'red');r.host(h.host,'approve',h.red);assert.equal(r.view(h.red).me.team,'black');assert.equal(r.view(h.red).myVote,null);r.leave(h.red);r.join(h.red,'Rejoined','player');assert.equal(r.view(h.red).me.team,'black');assert.throws(()=>r.chooseTeam(h.red,'red'),/khóa/);h.manager.close();});
test('opponents and guests never receive current tally, count, notice or private metrics',()=>{const h=setup(),r=h.room;r.join(h.red,'Red','player');r.chooseTeam(h.red,'red');r.join(h.black,'Black','player');r.chooseTeam(h.black,'black');r.join(h.guest,'Guest','guest');r.vote(h.red,r.view(h.red).game.windowId,'1');assert.deepEqual(r.view(h.red).game.tally,{'1':1});assert.deepEqual(r.view(h.host).game.tally,{'1':1});for(const id of [h.black,h.guest]){const v=r.view(id);assert.deepEqual(v.game.tally,{});assert.equal(v.game.voterCount,0);assert.equal(v.game.metrics.acceptedVotes,0);assert.deepEqual(v.game.notices,[]);assert.deepEqual(v.game.legalMoves,[]);assert.equal(v.myVote,null);}h.advance(5000);assert.deepEqual(r.view(h.black).game.lastTally,{});assert.deepEqual(r.view(h.guest).game.lastTally,{});h.manager.close();});
test('guest has no vote, may request promotion; only host can moderate',()=>{const h=setup(),r=h.room;r.join(h.guest,'Guest','guest');assert.throws(()=>r.chooseTeam(h.guest,'red'),/Guest/);assert.throws(()=>r.vote(h.guest,1,'1'),/vào đội/);r.requestTeam(h.guest,'red');assert.throws(()=>r.host(h.guest,'approve',h.guest),/Chỉ host/);r.host(h.host,'approve',h.guest);assert.equal(r.view(h.guest).me.kind,'player');assert.equal(r.view(h.guest).me.team,'red');h.manager.close();});
test('capacity includes guests and reserves host seat; team caps apply to host moves',()=>{const h=setup();const r=h.manager.create(h.host,'Host','Caps',{game:'tictactoe',maxPeople:3,redLimit:1,blackLimit:1});r.join(h.red,'Red','player');r.chooseTeam(h.red,'red');r.join(h.guest,'G','guest');assert.throws(()=>r.join(h.black,'B','player'),/đủ người/);assert.throws(()=>r.host(h.host,'move',h.guest,'red'),/đủ người/);r.leave(h.host);assert.throws(()=>r.join(h.black,'B','player'),/đủ người/);r.join(h.host,'Host back','player');assert.equal(r.view(h.host).members.length,3);h.manager.close();});
test('kick allows explicit rejoin, ban survives restart, unban restores ability to join',()=>{const h=setup();let r=h.room;r.join(h.red,'Red','player');r.chooseTeam(h.red,'red');r.host(h.host,'kick',h.red);assert.throws(()=>r.view(h.red),/rời phòng/);r.join(h.red,'Red','player');r.host(h.host,'ban',h.red);assert.throws(()=>r.join(h.red,'New name','guest'),/bị cấm/);r=h.restart();assert.throws(()=>r.join(h.red,'X','player'),/bị cấm/);r.host(h.host,'unban',h.red);r.join(h.red,'Back','player');assert.equal(r.view(h.red).me.team,'red');h.manager.close();});
test('empty turn automatically plays a legal random move instead of waiting',()=>{const h=setup(),r=h.room;const before=r.view(h.host).game;assert.equal(before.phase,'voting');h.advance(5000);const after=r.view(h.host).game;assert.equal(after.phase,'revealing');assert.equal(after.metrics.moves,1);assert.equal(after.board.cells?.filter(Boolean).length,1);assert.deepEqual(after.lastTally,{});h.advance(2000);assert.equal(r.view(h.host).game.activeTeam,'black');h.manager.close();});
test('match timeout draws and stops; host restarts with new absolute deadline',()=>{const h=setup(),r=h.room;h.advance(60000);assert.equal(r.view(h.host).game.phase,'finished');assert.equal(r.view(h.host).game.outcome?.winner,null);const moves=r.view(h.host).game.metrics.moves;h.advance(60000);assert.equal(r.view(h.host).game.metrics.moves,moves);r.host(h.host,'restart');assert.equal(r.view(h.host).game.phase,'voting');assert.equal(r.view(h.host).game.gameId,2);assert.ok(r.meta.matchDeadline>r.view(h.host).game.serverNow);h.manager.close();});
test('settings validate limits; guests disabled; closing room revokes all access',()=>{assert.throws(()=>validateSettings({maxPeople:2,redLimit:3,blackLimit:1}),/Giới hạn/);const h=setup();const r=h.manager.create(h.host,'Host','Private',{allowGuests:false});assert.throws(()=>r.join(h.guest,'Guest','guest'),/không cho phép/);r.host(h.host,'close');assert.throws(()=>r.view(h.host),/đã đóng/);assert.throws(()=>r.join(h.red,'Red','player'),/đã đóng/);h.manager.close();});
test('room metadata and engine team changes rollback together on SQLite failure',()=>{const h=setup(),r=h.room;r.join(h.red,'Red','player');r.store.db.exec("CREATE TRIGGER fail_meta BEFORE UPDATE ON room_meta BEGIN SELECT RAISE(ABORT, 'disk error'); END;");assert.throws(()=>r.chooseTeam(h.red,'red'),/disk error/);assert.equal(r.view(h.red).me.team,null);assert.equal(r.engine.playerState(h.red).member,null);h.manager.close();});
test('rooms do not share board, participants, or votes',()=>{const h=setup();const other=h.manager.create(h.black,'Other host','Other',{game:'xiangqi'});h.room.chooseTeam(h.host,'red');h.room.vote(h.host,1,'1');assert.equal(other.view(h.black).game.voterCount,0);assert.throws(()=>other.view(h.host),/rời phòng/);assert.notEqual(other.meta.code,h.room.meta.code);h.manager.close();});
test('HTTP derives identity from remote IP, ignores forged forwarding and removes old bypass APIs',async()=>{const dir=mkdtempSync(join(tmpdir(),'kyhoi-http-'));const {app}=await createRoomServer({directory:dir,serveStatic:false,timer:false});try{
  const call=(method:'GET'|'POST',url:string,ip:string,payload?:object,headers:Record<string,string>={})=>app.inject({method,url,remoteAddress:ip,payload,headers});
  const created=await call('POST','/api/rooms','10.0.0.1',{name:'Host',settings:{game:'tictactoe'}});assert.equal(created.statusCode,201);const code=created.json().code,hostId=created.json().me.id;
  const forged=await call('POST',`/api/rooms/${code}/join`,'10.0.0.2',{name:'Fake host'},{'x-forwarded-for':'10.0.0.1'});assert.notEqual(forged.json().me.id,hostId);assert.equal(forged.json().isHost,false);
  assert.equal((await call('POST',`/api/rooms/${code}/host`,'10.0.0.2',{action:'restart'})).statusCode,403);
  const same=await call('POST',`/api/rooms/${code}/join`,'::ffff:10.0.0.1',{name:'Same IP'});assert.equal(same.json().isHost,true);assert.equal(same.json().me.id,hostId);
  assert.equal((await call('GET','/api/state','10.0.0.2')).statusCode,404);assert.equal((await call('POST','/api/mock/comment','10.0.0.2',{userId:hostId,text:'!team do'})).statusCode,404);
  assert.equal((await call('POST',`/api/rooms/${code}/leave`,'10.0.0.1',{}, {origin:'https://attacker.example'})).statusCode,403);
}finally{await app.close();}});
test('only explicitly trusted proxy may provide client IP',async()=>{const dir=mkdtempSync(join(tmpdir(),'kyhoi-proxy-'));const {app}=await createRoomServer({directory:dir,trustProxy:'127.0.0.1',serveStatic:false,timer:false});try{const a=await app.inject({method:'POST',url:'/api/rooms',remoteAddress:'127.0.0.1',headers:{'x-forwarded-for':'10.0.0.1'},payload:{name:'A'}});const code=a.json().code;const b=await app.inject({method:'POST',url:`/api/rooms/${code}/join`,remoteAddress:'127.0.0.1',headers:{'x-forwarded-for':'10.0.0.2'},payload:{name:'B'}});assert.notEqual(a.json().me.id,b.json().me.id);assert.equal(b.json().isHost,false);}finally{await app.close();}});
