// <auto-generated />
using System;
using Farm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Farm.Data.Migrations
{
    [DbContext(typeof(AuraFarming))]
    [Migration("20261004132946_InitialAuraFarming")]
    partial class InitialAuraFarming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Farm.Data.Entities.PlatformBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("PlatformBookmarks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#238636",
                            CreatedAtUtc = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "GitHub repositories, PRs & code contributions",
                            DisplayOrder = 1,
                            IsActive = true,
                            Platform = "GitHub",
                            PlatformId = "quocchungthan",
                            Url = "https://github.com/quocchungthan"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#ff0050",
                            CreatedAtUtc = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Short-form tech demos and vibe coding feeds",
                            DisplayOrder = 2,
                            IsActive = true,
                            Platform = "TikTok",
                            PlatformId = "quocchungthan",
                            Url = "https://www.tiktok.com/@quocchungthan"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#1877f2",
                            CreatedAtUtc = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Community updates and social networking",
                            DisplayOrder = 3,
                            IsActive = true,
                            Platform = "Facebook",
                            PlatformId = "quocchungthan",
                            Url = "https://www.facebook.com/quocchungthan"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#e4405f",
                            CreatedAtUtc = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dev stories, behind the scenes, and life feeds",
                            DisplayOrder = 4,
                            IsActive = true,
                            Platform = "Instagram",
                            PlatformId = "quocchungthan",
                            Url = "https://www.instagram.com/quocchungthan"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#0078d4",
                            CreatedAtUtc = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pipelines, work items, and backlog gigs",
                            DisplayOrder = 5,
                            IsActive = true,
                            Platform = "Azure DevOps",
                            PlatformId = "quocchungthan",
                            Url = "https://dev.azure.com/quocchungthan"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#ea4335",
                            CreatedAtUtc = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Direct client inquiries & software gig proposals",
                            DisplayOrder = 6,
                            IsActive = true,
                            Platform = "Gmail",
                            PlatformId = "chung@eldervibe.dev",
                            Url = "mailto:chung@eldervibe.dev"
                        });
                });

            modelBuilder.Entity("Farm.Data.Entities.WebsiteMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("DeveloperName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WebsiteMetadata", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "if you are seeking for a software developer to talk to, it's me here",
                            DeveloperName = "quocchungthan",
                            RepositoryUrl = "https://github.com/quocchungthan/internet-facing",
                            Title = "a Elder engineer learn to vibe code",
                            UpdatedAtUtc = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
